nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Content-Disposition']
        max_age: 3600
        hosts: []
        origin_regex: false
    paths:
        '^/':
            allow_origin: ['*']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
            expose_headers: ['Content-Disposition']
            max_age: 3600